packages:
  - '@guidogerb/components/api-client'
  - '@guidogerb/components/auth'
  - '@guidogerb/components/menu'
  - '@guidogerb/components/pages/*'
  - '@guidogerb/components/router/*'
  - '@guidogerb/components/sw'
  - '@guidogerb/components/ui'
  - '@guidogerb/css'
  - '@guidogerb/footer'
  - '@guidogerb/header'
  - websites/garygerber.com
  - websites/guidogerbpublishing.com
  - websites/picklecheeze.com
  - websites/this-is-my-story.org
  - websites/stream4cloud.com

ignoredBuiltDependencies:
  - esbuild
