packages:
  - '@guidogerb/components/ai-support'
  - '@guidogerb/components/analytics'
  - '@guidogerb/components/api-client'
  - '@guidogerb/components/app'
  - '@guidogerb/components/auth'
  - '@guidogerb/components/catalog'
  - '@guidogerb/components/menu'
  - '@guidogerb/components/pages/*'
  - '@guidogerb/components/point-of-sale'
  - '@guidogerb/components/router/*'
  - '@guidogerb/components/shopping-cart'
  - '@guidogerb/components/storage'
  - '@guidogerb/components/sw'
  - '@guidogerb/components/ui'
  - '@guidogerb/config'
  - '@guidogerb/css'
  - '@guidogerb/enums'
  - '@guidogerb/footer'
  - '@guidogerb/header'
  - '@guidogerb/hooks'
  - '@guidogerb/util'
  - 'websites/*'

ignoredBuiltDependencies:
  - esbuild
