import './css/index.scss'
// eslint-disable-next-line import/extensions
import packageJson from './package.json'

export { childrenMenuTypes } from './js/enumerations/childrenMenuTypes'
export { PopupPlacement } from './js/enumerations/popupPlacement'
export { events } from './js/enumerations/events'
export { sizes } from './js/enumerations/sizes'
export { loadHeader, removeHeader } from './js/lifecycle/lifecycle'
export { renderDOMSingle } from './js/misc/renderDOMSingle'
export { defaultSettings } from './js/settings/defaultSettings'
export { getHeaderSettings } from './js/settings/getHeaderSettings.js'
export { setFooterSettings, setHeaderSettings } from './js/settings/settings'
export { popupFocusHandler } from './js/misc/popupFocusHandler'
export { HeaderContext } from './HeaderContext'
export { HeaderContextProvider } from './HeaderContextProvider'
