AWSTemplateFormatVersion: '2010-09-09'
Description: Stream4Cloud OpenSearch Serverless - collection + security policies
Parameters:
  CollectionName:
    Type: String
    Default: s4c-search
  AdminPrincipalArn:
    Type: String
    Description: IAM ARN (user/role) granted data access
  AllowFromPublic:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: Whether to expose the collection publicly. Set to 'false' for private VPC-only access.
  SourceVpceIds:
    Type: String
    Default: ''
    AllowedPattern: '^$|^vpce-[A-Za-z0-9]+(,vpce-[A-Za-z0-9]+)*$'
    Description: Comma-separated list of VPC endpoint IDs permitted when AllowFromPublic is 'false'.

Rules:
  RequireVpceIdsForPrivateAccess:
    RuleCondition: !Equals [!Ref AllowFromPublic, 'false']
    Assertions:
      - Assert: !Not [!Equals [!Ref SourceVpceIds, '']]
        AssertDescription: Provide SourceVpceIds when disabling public access.

Conditions:
  AllowPublicAccess: !Equals [!Ref AllowFromPublic, 'true']

Resources:
  EncryptionPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub '${CollectionName}-enc'
      Type: encryption
      Policy: !Sub |
        {
          "Rules": [
            {"ResourceType": "collection", "Resource": ["collection/${CollectionName}"]}
          ],
          "AWSOwnedKey": true
        }

  NetworkPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub '${CollectionName}-net'
      Type: network
      Policy: !If
        - AllowPublicAccess
        - !Sub |
            {"Rules":[{"ResourceType":"collection","Resource":["collection/${CollectionName}"]},{"ResourceType":"dashboard","Resource":["dashboard/${CollectionName}"]}],"AllowFromPublic":true}
        - !Sub
            - |
              {"Rules":[{"ResourceType":"collection","Resource":["collection/${CollectionName}"]},{"ResourceType":"dashboard","Resource":["dashboard/${CollectionName}"]}],"SourceVPCEs":["${QuotedVpces}"],"AllowFromPublic":false}
            - { QuotedVpces: !Join ['","', !Split [',', !Ref SourceVpceIds]] }

  DataAccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    Properties:
      Name: !Sub '${CollectionName}-data'
      Type: data
      Policy: !Sub |
        [
          {
            "Rules":[
              {"ResourceType":"collection","Resource":["collection/${CollectionName}"],"Permission":["aoss:CreateCollectionItems","aoss:DescribeCollectionItems","aoss:ReadDocument","aoss:WriteDocument"]},
              {"ResourceType":"index","Resource":["index/${CollectionName}/*"],"Permission":["aoss:CreateIndex","aoss:DescribeIndex","aoss:ReadDocument","aoss:WriteDocument"]}
            ],
            "Principal":[ "${AdminPrincipalArn}" ]
          }
        ]

  Collection:
    Type: AWS::OpenSearchServerless::Collection
    Properties:
      Name: !Ref CollectionName
      Type: SEARCH

Outputs:
  CollectionId:
    Value: !GetAtt Collection.Id
  CollectionEndpoint:
    Value: !GetAtt Collection.CollectionEndpoint
