name: Build (CI)

on:
  pull_request:
    branches: [ "main", "prod" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: '20.19.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create .env file from secret
      - name: Create website/.env file
        run: |
          echo "${{ secrets.VITE_ENV }}" > website/.env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: 'npm'

      - name: Configure npm for GitHub Packages
        env:
          NPMRC_TOKEN: ${{ secrets.NPMRC_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ env.NPMRC_TOKEN }}" >> ~/.npmrc
          echo "@guidogerb:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - name: Install dependencies (CI)
        run: npm ci

      - name: Build (branch-specific)
        run: |
          if [ "${{ github.base_ref || github.ref_name }}" = "prod" ]; then
            npm run ci:deploy:prod
          else
            npm run ci:deploy:main
          fi

      - name: Save website build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: website-dist
          path: website/dist
