name: Build (CI)

on:
  pull_request:
    branches: [ "main", "prod" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: '20.19.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create .env file from secret
      - name: Create .env file
        run: |
          echo "${{ secrets.VITE_ENV }}" > .env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: 'npm'

      - name: Configure npm for GitHub Packages
        env:
          NPMRC_TOKEN: ${{ secrets.NPMRC_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ env.NPMRC_TOKEN }}" >> ~/.npmrc
          echo "@guidogerb:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - name: Install dependencies (workspaces)
        run: npm install

      - name: Build monorepo
        run: npm run build

      - name: Save website build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: website-dist
          path: website/dist
