name: Build and Test (CI)

on:
  push:
    branches: ['main', 'prod']
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: '20.19.0'

jobs:
  build:
    name: Build and Test All Websites
    runs-on: ubuntu-latest
    env:
      NPMRC_TOKEN: ${{ secrets.NPMRC_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure npm auth for GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${NPMRC_TOKEN}" >> ~/.npmrc
        env:
          NPMRC_TOKEN: ${{ env.NPMRC_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Lint all packages
        run: npm run lint
        continue-on-error: true

      - name: Format check
        run: pnpm format:check

      - name: Write .env files
        run: |
          echo "${{ secrets.GARYGERBER_VITE_ENV }}" > websites/garygerber.com/.env
          echo "${{ secrets.GUIDOGERBPUBLISHING_VITE_ENV }}" > websites/guidogerbpublishing.com/.env
          echo "${{ secrets.PICKLECHEEZE_VITE_ENV }}" > websites/picklecheeze.com/.env
          echo "${{ secrets.STREAM4CLOUD_VITE_ENV }}" > websites/stream4cloud.com/.env
          echo "${{ secrets.THIS_IS_MY_STORY_VITE_ENV }}" > websites/this-is-my-story.com/.env

      - name: Build components
        run: pnpm -r build

      - name: Check a dist folder for existence after builds
        run: |
          ls -l websites/guidogerbpublishing.com
          ls -l websites/guidogerbpublishing.com/dist || echo "dist folder missing"

      - name: Test branch-specific build (guidogerbpublishing.com)
        run: |
          if [ "${{ github.base_ref || github.ref_name }}" = "prod" ]; then
            pnpm --filter websites-guidogerbpublishing build:prod-bundle
          else
            pnpm --filter websites-guidogerbpublishing build:staging
          fi

      - name: Test branch-specific build (garygerber.com)
        run: |
          if [ "${{ github.base_ref || github.ref_name }}" = "prod" ]; then
            pnpm --filter websites-garygerber build:prod-bundle
          else
            pnpm --filter websites-garygerber build:staging
          fi

      - name: Test branch-specific build (picklecheeze.com)
        run: |
          if [ "${{ github.base_ref || github.ref_name }}" = "prod" ]; then
            pnpm --filter websites-picklecheeze build:prod-bundle
          else
            pnpm --filter websites-picklecheeze build:staging
          fi

      - name: Test branch-specific build (this-is-my-story.org)
        run: |
          if [ "${{ github.base_ref || github.ref_name }}" = "prod" ]; then
            pnpm --filter websites-this-is-my-story build:prod-bundle
          else
            pnpm --filter websites-this-is-my-story build:staging
          fi

      - name: Test branch-specific build (stream4cloud.com)
        run: |
          if [ "${{ github.base_ref || github.ref_name }}" = "prod" ]; then
            pnpm --filter websites-stream4cloud build:prod-bundle
          else
            pnpm --filter websites-stream4cloud build:staging
          fi

      - name: Save build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: all-websites-dist-${{ github.head_ref || github.ref_name }}
          path: websites/*/dist
          retention-days: 7
