name: deploy

on:
  workflow_dispatch:
    inputs:
      site:
        description: 'Site to deploy (folder under websites)'
        required: true
        default: 'stream4cloud.com'
        type: choice
        options: [stream4cloud.com, garygerber.com, guidogerbpublishing.com, picklecheeze.com, this-is-my-story.org]
      aws_region:
        description: 'AWS region'
        required: true
        default: 'us-east-1'
      bucket:
        description: 'Target S3 bucket name'
        required: true
      distribution_id:
        description: 'CloudFront Distribution ID'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build selected site
        run: pnpm --filter websites/${{ inputs.site }} build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}

      - name: Upload to S3
        run: |
          aws s3 sync websites/${{ inputs.site }}/dist s3://${{ inputs.bucket }}/ --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ inputs.distribution_id }} --paths "/*"

