name: deploy

on:
  workflow_dispatch:
    inputs:
      site:
        description: 'Site to deploy (folder under websites)'
        required: true
        default: 'guidogerbpublishing.com'
        type: choice
        options:
          [
            stream4cloud.com,
            garygerber.com,
            guidogerbpublishing.com,
            picklecheeze.com,
            this-is-my-story.org,
          ]
      aws_region:
        description: 'AWS region'
        required: true
        default: 'us-east-1'
      bucket:
        description: 'Target S3 bucket name'
        required: true
        default: 'ggp-websites'
      distribution_id:
        description: 'CloudFront Distribution ID'
        required: true
        default: 'E1MM1G0JP81M1R'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      NPMRC_TOKEN: ${{ secrets.NPMRC_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build selected site
        run: pnpm --filter websites/${{ inputs.site }} build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}

      - name: Upload to S3 (tenant prefix)
        env:
          SITE: ${{ inputs.site }}
          BUCKET: ${{ inputs.bucket }}
        run: |
          set -euo pipefail
          SRC="websites/${SITE}/dist"
          DEST="s3://${BUCKET}/${SITE}/"
          aws s3 sync "$SRC" "$DEST" --delete

      - name: Compute invalidation path
        id: inv
        env:
          SITE: ${{ inputs.site }}
          PREFIX_ONLY: ${{ inputs.invalidate_prefix_only }}
        run: |
          if [ "${PREFIX_ONLY}" = "true" ]; then
            echo "paths=/${SITE}/*" >> "$GITHUB_OUTPUT"
          else
            echo "paths=/*" >> "$GITHUB_OUTPUT"
          fi

      - name: Invalidate CloudFront
        env:
          DIST_ID: ${{ inputs.distribution_id }}
          PATHS: ${{ steps.inv.outputs.paths }}
        run: |
          aws cloudfront create-invalidation --distribution-id "${DIST_ID}" --paths "${PATHS}"